#!/bin/bash


python writeManualSubRulesToDB.py
python Crawl_foodsubs.com.py 
python entityMappingToRDF.py
python Word2VecStream.py -f data/word2vecstream.ing.permute.sub.out --substitute True
word2vec/bin/word2vec -train data/word2vecstream.ing.permute.sub.out -output data/word2vec.ing.permute.sub.out.txt -negative 5 -cbow 1
python WriteWord2VecToDB.py --vecname word2vec -f data/word2vec.ing.permute.sub.out.txt
python RecipeClassification.py
python ComputeAndSaveRecipeVecs.py
python CollectBasicStats.py
#python legacyFeedback.py --mongo $1
#python SubstitutionEngine.py  --ids $1



