logging:
  path: logs

security:
  basic:
    enabled: true
  user:
    name: demo
    password: java
    
spring:
  application:
    name:  mfe-rest-demo 
  data:
    mongodb: 
      host: localhost:27017
      database: fullset
      
#     host: ds145728-a0.mlab.com:45728
#     password: javadevelop
#     username: java
#     database: myfavoreats-develop    
    
#      host: ds151719-a0.mlab.com:51719
#     database: mfe-front-end
#     username: mfe-front
#     password: mfe-front
      
#     host: ds155718.mlab.com:55718
#     database: java-demo
#     username: javademo
#     password: javademo
      
      
      
      
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
