package com.mfe.parser;
import com.mfe.parser.RecipeToken;
import com.mfe.parser.TokenClass;

%%

%{
  // user code
  public RecipeToken getToken( TokenClass sym) {  return new RecipeToken( sym , yytext(), yyline, yycolumn, yycolumn + yylength() -1); }

%}

%class DishLexer
%implements JflexLex
%pack
%function nextToken
%unicode
%line
%column
%ignorecase
%type RecipeToken
%ignorecase
%eofval{
  { return new RecipeToken (TokenClass . EOF); }
%eofval}

LineTerminator = \r|\n|\r\n
//InputCharacter = [^\r\n]
WhiteSpace = [ \t]
AnySpace = {LineTerminator} | {WhiteSpace} | [\f]

PUNC    = {WhiteSpace}|\p{Punctuation}|\f|{LineTerminator}
PLURAL =  y|s|es|ies|ii
ADJ  = {ADJ_S}{PUNC}
DISH = {DISH_S}{PLURAL}?{PUNC}


ADJ_S =  packed
        |"not packed"
        | level
        | chopped
        | large
        | extra
        | shredded
        | sifted
        | small
        | heaping
        | medium
        | lg
        | sm
        | diced
        | boiled
        | bbq
        | baked
        | fried
        | dried
        | diced
        | sliced
        | picked
        | frozen
        | salted
        | stewed
        | md

 


DISH_S =  "nando's famous flame-grilled peri peri chicken"
| "peanut butter chocolate chip oatmeal cookie"
| "chocolate-cherry heart smart cookies"
| "chongqing spicy deep-fried chicken"
| "the great british cheese festival"
| "maple roasted butternut squash"
| "bacon, egg and cheese sandwich"
| "banana chocolate chip cookies"
| "strawberry-orange milk shake"
| "chicken & broccoli casserole"
| "whipped cream cheese spread"
| "cold chicken cooked in wine"
| "chicken and duck blood soup"
| "chicken fettuccine alfredo"
| "cheese and pickle sandwich"
| "peanut butter & chocolate"
| "baked macaroni and cheese"
| "sweet and sour meatballs"
| "stuffed butternut squash"
| "smoked salmon cheesecake"
| "roasted butternut squash"
| "oxford companion to food"
| "chicken and mushroom pie"
| "butternut squash risotto"
| "roasted brussel sprouts"
| "chocolate dipping sauce"
| "butternut squash muffin"
| "swiss chicken casserole"
| "sloppy joe biscuit cups"
| "refreshing spicy summer"
| "lucerne cheese festival"
| "jellied cranberry sauce"
| "ham and cheese sandwich"
| "fujian red wine chicken"
| "cinnamon apple struesel"
| "thin crust pizza dough"
| "thai green curry paste"
| "swedish meatball sauce"
| "sesame ginger dressing"
| "chocolate chip pancake"
| "whipped cream frosting"
| "smoothies &amp"
| "húsleves chicken soup"
| "california cheese maki"
| "white chocolate sauce"
| "toasted pumpkin seeds"
| "sticky toffee pudding"
| "pumpkin spice pudding"
| "pumpkin cinnamon roll"
| "puddings and custards"
| "peanut butter fingers"
| "mashed sweet potatoes"
| "macaroni &amp"
| "cream of chicken soup"
| "cream cheese frosting"
| "yeung chow fried rice"
| "whipped cream topping"
| "tuscan garlic chicken"
| "sweet brussel sprouts"
| "spicy brussel sprouts"
| "sicilian orange salad"
| "savory sweet potatoes"
| "sauces and condiments"
| "monte cristo sandwich"
| "general tso's chicken"
| "garlic sweet potatoes"
| "cinnamon apple muffin"
| "chocolate chip cookie"
| "chinese chicken salad"
| "chicken and dumplings"
| "champagne vinaigrette"
| "butternut squash soup"
| "whole wheat tortilla"
| "strawberry shortcake"
| "savory bread pudding"
| "pumpkin cream cheese"
| "peanut butter cookie"
| "lemon honey dressing"
| "cream cheese chicken"
| "coconut bread recipe"
| "chicken tikka masala"
| "cherry ice cream pie"
| "blueberry cheesecake"
| "almond butter cookie"
| "thai red curry paste"
| "sweet n sour chicken"
| "strawberry lemon jam"
| "roasted pumpkin seed"
| "rice krispies treats"
| "regional street food"
| "peanut butter hummus"
| "korean fried chicken"
| "hot chicken sandwich"
| "graham cracker crust"
| "fried capellini cake"
| "crispy fried chicken"
| "chocolate chip icing"
| "chicken and broccoli"
| "brussel sprout salad"
| "broccoli cheese soup"
| "bean sprouts chicken"
| "alternative gazpacho"
| "whole wheat cookies"
| "sweet potato muffin"
| "roasted red peppers"
| "pumpkin coffee cake"
| "peanut butter glaze"
| "new york cheesecake"
| "hashbrown casserole"
| "gluten free pancake"
| "chocolate chip cake"
| "caramelized veggies"
| "whole grain pancake"
| "sweet potato spread"
| "sweet potato hummus"
| "spaghetti casserole"
| "maple whipped creme"
| "macaroni and cheese"
| "chicken noodle soup"
| "cheddar bay biscuit"
| "american fried rice"
| "sour cream cookies"
| "roasted vegetables"
| "roasted red pepper"
| "poppyseed dressing"
| "peanut butter cake"
| "oven fried chicken"
| "ice cream sandwich"
| "garlic chili sauce"
| "french fried onion"
| "cranberry balsamic"
| "chocolate macaroon"
| "chocolate cupcakes"
| "cherry pie filling"
| "buttermilk chicken"
| "baked french toast"
| "vegetarian lasanga"
| "vegetarian lasagna"
| "vegetable sandwich"
| "thalassery biryani"
| "sweet saffron rice"
| "sweet chilli sauce"
| "submarine sandwich"
| "strawberry dessert"
| "spicy peanut sauce"
| "spicy orange sauce"
| "spiced buttercream"
| "snake bite chicken"
| "smoothies & shakes"
| "rotisserie chicken"
| "roasted broccolini"
| "rice krispie treat"
| "pumpkin spice bars"
| "pumpkin cheesecake"
| "mango mint martini"
| "king ranch chicken"
| "honey sweet potato"
| "green papaya salad"
| "gingerbread cookie"
| "fuli roast chicken"
| "engagement chicken"
| "cream cheese icing"
| "coronation chicken"
| "circassian chicken"
| "chicken parmigiana"
| "chicken fried rice"
| "chicken enchiladas"
| "cauliflower cheese"
| "buttermilk pancake"
| "brown stew chicken"
| "breakfast sandwich"
| "barbeque spare rib"
| "baked sweet potato"
| "vegan carrot cake"
| "vanilla ice cream"
| "triple cream brie"
| "tarte aux fraises"
| "swedish meatballs"
| "stuffed artichoke"
| "spinach-artichoke"
| "shrimps and grits"
| "roasted vegetable"
| "peanut butter cup"
| "merluzzo al forno"
| "garlic pull apart"
| "encrusted tilapia"
| "devil's food cake"
| "cream of mushroom"
| "cranberry dessert"
| "cinnamon frosting"
| "chocolate souffle"
| "black bean burger"
| "yorkshire pudding"
| "white cut chicken"
| "whimsical dessert"
| "wheat pizza dough"
| "turtle cheesecake"
| "tomato basil soup"
| "sweet & sour ribs"
| "sweet & sour pork"
| "spring roll sauce"
| "soy sauce chicken"
| "pumpkin pie spice"
| "pumpkin ice cream"
| "paneer manchurian"
| "kimchi bokkeumbap"
| "hollandaise sauce"
| "girl scout cookie"
| "fried cauliflower"
| "french onion soup"
| "faccia de vecchia"
| "chocolate-covered"
| "chocolate oatmeal"
| "chocolate pancake"
| "cauliflower crust"
| "breakfast burrito"
| "barberton chicken"
| "zucchini muffins"
| "warm vinaigrette"
| "unleavened bread"
| "sweet potato pie"
| "sunflower butter"
| "shrimp and grits"
| "shredded chicken"
| "roasted potatoes"
| "roasted chickpea"
| "red pepper jelly"
| "pumpkin streusel"
| "pumpkin smoothie"
| "pumpkin pancakes"
| "protein smoothie"
| "mac &amp"
| "gingerbread cake"
| "funeral potatoes"
| "fruit cheesecake"
| "dessert smoothie"
| "crustless quiche"
| "coconut frosting"
| "chocolate muffin"
| "cauliflower rice"
| "buttered chicken"
| "baked potato dip"
| "baked cheesecake"
| "apple bundt cake"
| "zucchini fritter"
| "white wine punch"
| "white bean chili"
| "whipped dressing"
| "wenchang chicken"
| "vegetarian chili"
| "vegetarian pizza"
| "vanilla pancakes"
| "teriyaki chicken"
| "tandoori chicken"
| "stuffed zucchini"
| "stuffed mushroom"
| "squash casserole"
| "speculoos spread"
| "senate bean soup"
| "scallion pancake"
| "salsa verde beef"
| "rice noodle roll"
| "red pepper sauce"
| "processed cheese"
| "pickled cucumber"
| "pasta vegetables"
| "orange marmalade"
| "oatmeal smoothie"
| "muffins/cupcakes"
| "mozzarella stick"
| "lettuce sandwich"
| "lemon pound cake"
| "kung pao chicken"
| "italian dressing"
| "herbed cocktails"
| "harvest sandwich"
| "hard boiled eggs"
| "easy pumpkin pie"
| "dagwood sandwich"
| "cream-style corn"
| "cream of chicken"
| "cream style corn"
| "christmas cookie"
| "chocolate mousse"
| "chocolate fondue"
| "chickpea fritter"
| "chicken sandwich"
| "chicken parmesan"
| "chicken teriyaki"
| "cheese appetizer"
| "chai latte scone"
| "buttermilk scone"
| "breakfast cookie"
| "blueberry muffin"
| "beggar's chicken"
| "beer cheese soup"
| "barbecue chicken"
| "applesauce bread"
| "yogurt pancakes"
| "white bean soup"
| "vegetable stock"
| "vegetable salad"
| "vegetable puree"
| "toasted walnuts"
| "toasted almonds"
| "spinach noodles"
| "spaghetti sauce"
| "shrimp cocktail"
| "sandwich cookie"
| "roasted veggies"
| "roasted almonds"
| "raspberry jello"
| "pumpkin risotto"
| "pumpkin muffins"
| "pumpkin granola"
| "pumpkin fritter"
| "pumpkin cookies"
| "pumpkin brownie"
| "protein cookies"
| "oatmeal pancake"
| "oatmeal cookies"
| "mashed potatoes"
| "hazelnut muffin"
| "gingerbread bar"
| "flavored hummus"
| "dulche de leche"
| "deviled sausage"
| "cranberry sauce"
| "compound butter"
| "coconut pudding"
| "cinnamon butter"
| "chili con carne"
| "chickpea cookie"
| "chicken pot pie"
| "caribbean bread"
| "caeser dressing"
| "buffalo chicken"
| "breakfast crepe"
| "beef stroganoff"
| "banana fritters"
| "angel food cake"
| "almond macaroon"
| "whipped topping"
| "vegetarian stew"
| "vegetarian soup"
| "vegetable broth"
| "types of cheese"
| "tomato omelette"
| "thai fried rice"
| "stuffed peppers"
| "stuffed pumpkin"
| "stuffed chicken"
| "strawberry soup"
| "stewed tomatoes"
| "soups and stews"
| "salsa con queso"
| "roasted chicken"
| "rice vermicelli"
| "reuben sandwich"
| "reindeer cheese"
| "red velvet cake"
| "pudding/custard"
| "pork tenderloin"
| "pasta primavera"
| "macaroon cookie"
| "khao khluk kapi"
| "jubilee chicken"
| "herring as food"
| "grasshopper pie"
| "gobi manchurian"
| "glasswort salad"
| "gingerbread men"
| "fried aubergine"
| "flavored butter"
| "flat iron steak"
| "english muffins"
| "drunken chicken"
| "dong'an chicken"
| "cranberry salsa"
| "cookie sandwich"
| "coconut pancake"
| "chocolate glaze"
| "chile con queso"
| "chicken tractor"
| "chicken tatsuta"
| "chicken riggies"
| "chicken marsala"
| "chicken fingers"
| "chicken vesuvio"
| "chicken marengo"
| "cheese sandwich"
| "cheese on toast"
| "caesar dressing"
| "brownie pancake"
| "breakfast treat"
| "breaded chicken"
| "bourbon chicken"
| "bon bon chicken"
| "bearnaise sauce"
| "arroz con pollo"
| "airline chicken"
| "yogurt parfait"
| "warm breakfast"
| "vegetable dish"
| "vegetable cake"
| "vegan smoothie"
| "vegan sausages"
| "toasted pecans"
| "taco casserole"
| "sweet and sour"
| "steak sandwich"
| "spiced almonds"
| "snickerdoodles"
| "snicker doodle"
| "shrimp sausage"
| "shepherd's pie"
| "shellfish dish"
| "seafood paella"
| "scrambled eggs"
| "savory fritter"
| "savory custard"
| "salted caramel"
| "salad dressing"
| "roasted squash"
| "roasted pepper"
| "roasted garlic"
| "roasted apples"
| "rasberry sauce"
| "pumpkin yogurt"
| "pumpkin quiche"
| "pumpkin muffin"
| "pumpkin cookie"
| "pumpkin butter"
| "pie on a stick"
| "ice cream cake"
| "frozen dessert"
| "fish and chips"
| "fall ice cream"
| "fall breakfast"
| "encrusted fish"
| "crema mexicana"
| "collard greens"
| "cocoa chickpea"
| "cinnamon scone"
| "christmas cake"
| "chicken tender"
| "chicken cutlet"
| "chicken burger"
| "casserole stew"
| "carrot–fudge"
| "candied ginger"
| "candied citrus"
| "candied citron"
| "browned butter"
| "barbecue sauce"
| "banana dessert"
| "bacon meatloaf"
| "autumn pancake"
| "apple dumpling"
| "zucchini pasta"
| "zucchini bread"
| "wonton wrapper"
| "veggie lasanga"
| "texas potatoes"
| "takikomi gohan"
| "taco seasoning"
| "stuffed tomato"
| "stuffed squash"
| "stuffed pepper"
| "steak marinade"
| "smoked chicken"
| "sesame chicken"
| "sarson da saag"
| "salmon as food"
| "rice and gravy"
| "ranch dressing"
| "queso flameado"
| "protein muffin"
| "pimento cheese"
| "pickling spice"
| "pepperoni roll"
| "party potatoes"
| "parboiled rice"
| "orange chicken"
| "oatmeal cookie"
| "mashed pumpkin"
| "mac and cheese"
| "lemon meringue"
| "lemon dressing"
| "karela nu shak"
| "hatsuga genmai"
| "grilled cheese"
| "glorified rice"
| "glazed chicken"
| "garlic chicken"
| "flattened rice"
| "fish barbecque"
| "fall vegetable"
| "desserts sauce"
| "cuban sandwich"
| "cottage cheese"
| "coriander rice"
| "collard liquor"
| "coconut cookie"
| "cinnamon apple"
| "chocolate cake"
| "chilli chicken"
| "chicken tabaka"
| "chicken pastel"
| "chicken nugget"
| "chicken karahi"
| "chicken inasal"
| "chicken potpie"
| "chicken lahori"
| "chicken french"
| "chicken finger"
| "cherry cobbler"
| "cheesecake pie"
| "cheese pudding"
| "cashew chicken"
| "caldo de queso"
| "butter chicken"
| "brownie batter"
| "breakfast cake"
| "bisi bele bath"
| "bhuni khicuhri"
| "banana pancake"
| "baingan bharta"
| "asian dumpling"
| "arroz borracho"
| "animal cracker"
| "vegan cookies"
| "turkey burger"
| "tso's chicken"
| "tortilla soup"
| "torta di mele"
| "sweet fritter"
| "sticky toffee"
| "spaghetti-o's"
| "soft pretzels"
| "smoked salmon"
| "shrimp scampi"
| "shredded pork"
| "seafood salad"
| "seafood gravy"
| "savoury bread"
| "savory pastry"
| "rice porridge"
| "pupmpkin cake"
| "pumpkin bread"
| "pudding cakes"
| "praline sauce"
| "pots de creme"
| "pecan cookies"
| "pasta fagioli"
| "pan di spagna"
| "oatmeal bread"
| "mustard sauce"
| "hot chocolate"
| "fruit dessert"
| "fried noodles"
| "fall sherbert"
| "fall frosting"
| "dipping sauce"
| "dessert sauce"
| "crescent roll"
| "creme caramel"
| "cranberry pie"
| "couscous dish"
| "corn tortilla"
| "coconut curry"
| "cinnamon roll"
| "chocolate pie"
| "chicken stock"
| "cheese fondue"
| "buffalo sauce"
| "buche de noel"
| "bread pudding"
| "bouillabaisse"
| "birthday cake"
| "baked tilapia"
| "baked chicken"
| "apple dessert"
| "apple crumble"
| "almond butter"
| "yogurt mousse"
| "welsh rarebit"
| "waldorf salad"
| "vegan pancake"
| "vegan lasagna"
| "tortilla chip"
| "tollhouse pie"
| "thieboudienne"
| "tamate ka kut"
| "tacoseasoning"
| "stuffed shell"
| "stewed tomato"
| "spinach salad"
| "spiced pecans"
| "spaghetti pie"
| "snickerdoodle"
| "smoked cheese"
| "shrimp creole"
| "shepherds pie"
| "salted butter"
| "roast chicken"
| "rice and peas"
| "rice krispies"
| "raspberry pie"
| "raspberry jam"
| "pretzel crust"
| "potato latkes"
| "pico de gallo"
| "pickle relish"
| "pb&amp"
| "old fashioned"
| "mushroom soup"
| "mote de queso"
| "molasses cake"
| "melt sandwich"
| "mattar paneer"
| "maple oatmeal"
| "lemon chicken"
| "lazy varenyky"
| "khao kan chin"
| "jello pudding"
| "israeli salad"
| "honey mustard"
| "homebrew beer"
| "glace cherrie"
| "ghormeh sabzi"
| "general tso's"
| "fudge filling"
| "frozen yogurt"
| "fried chicken"
| "fall smoothie"
| "cupcakes/cake"
| "cucumber soup"
| "confit byaldi"
| "coconut crust"
| "chopped liver"
| "chile relleno"
| "chicken tikka"
| "chicken salad"
| "chicken patty"
| "chicken katsu"
| "chicken fries"
| "chicken curry"
| "chicken balls"
| "chicken pizza"
| "chicken pasta"
| "chicken divan"
| "chicken chili"
| "chicken broth"
| "chhena kheeri"
| "chhena jalebi"
| "cheddar sauce"
| "chateaubriand"
| "carrot ginger"
| "caramel sauce"
| "caprese salad"
| "brownie bites"
| "broccoli slaw"
| "brined cheese"
| "bandel cheese"
| "bandeja paisa"
| "banana muffin"
| "baked oatmeal"
| "baba ghanoush"
| "apple pancake"
| "apple galette"
| "yellow curry"
| "xmas cookies"
| "whoopie pies"
| "vegan yogurt"
| "vegan cheese"
| "turkey chili"
| "torte salate"
| "torta salata"
| "tikka masala"
| "tartar sauce"
| "sweet pastry"
| "spring rolls"
| "spotted dick"
| "seafood cake"
| "savory sauce"
| "sauteed meat"
| "rattatouille"
| "quinoa salad"
| "pumpkin stew"
| "pumpkin soup"
| "pumpkin loaf"
| "pumpkin cake"
| "pumpkin bars"
| "poultry dish"
| "potato pizza"
| "pot stickers"
| "pot de creme"
| "pork sliders"
| "poached eggs"
| "nonalcoholic"
| "monkey bread"
| "mini muffins"
| "marshmallows"
| "maple squash"
| "mac n cheese"
| "key lime pie"
| "jell-o shots"
| "hush puppies"
| "garlic bread"
| "fruit mousse"
| "fruit butter"
| "fried prawns"
| "fried onions"
| "french toast"
| "french onion"
| "flaxseed egg"
| "faux chicken"
| "fall pancake"
| "fall dessert"
| "fall cupcake"
| "en papillote"
| "deviled eggs"
| "creme brulee"
| "crab rangoon"
| "cosmopolitan"
| "cookie dough"
| "coconut cake"
| "clam chowder"
| "chicken wing"
| "cheese bread"
| "cashew glaze"
| "candied yams"
| "candied nuts"
| "brownie cake"
| "brown butter"
| "black forest"
| "biscuit cake"
| "berry butter"
| "banana split"
| "banana cream"
| "banana bread"
| "baked alaska"
| "bacon cookie"
| "autumn salad"
| "asian noodle"
| "apple pastry"
| "apple muffin"
| "apple crisps"
| "apple baking"
| "zereshk polo"
| "winter salad"
| "winter pizza"
| "tongan toast"
| "tomato sauce"
| "tomato basil"
| "texas caviar"
| "swiss fondue"
| "sugar cookie"
| "stuffing mix"
| "stewing beef"
| "stewed apple"
| "spiced apple"
| "spanish rice"
| "sobe martini"
| "smoked trout"
| "simple syrup"
| "shwe yin aye"
| "shrimp cream"
| "shrimp pizza"
| "shahi paneer"
| "sesame sauce"
| "samlar machu"
| "sami zubaida"
| "salt-crusted"
| "salmon cakes"
| "saffron rice"
| "rotweinsauce"
| "rice pudding"
| "rice noodles"
| "pumpkni soup"
| "pumpkin tart"
| "pumpkin roll"
| "pulot tartal"
| "press cookie"
| "potato salad"
| "potato wedge"
| "pilgrims pie"
| "peanut sauce"
| "pastry cream"
| "pasta filata"
| "pasta sauces"
| "paneer tikka"
| "pancit bihon"
| "palak paneer"
| "noodle salad"
| "nasi tumpang"
| "mulligatawny"
| "mulled cider"
| "mornay sauce"
| "monte cristo"
| "mock risotto"
| "mixed pickle"
| "lettuce wrap"
| "lemon cookie"
| "khoya paneer"
| "khira sagara"
| "khao tom pla"
| "khao tom mat"
| "khao man kai"
| "kabuli palaw"
| "kaasstengels"
| "jerk chicken"
| "irish coffee"
| "instant rice"
| "htamin baung"
| "hayashi rice"
| "green cheese"
| "greek sweets"
| "garden salad"
| "fromage fort"
| "fried noodle"
| "french fries"
| "dinner rolls"
| "cream cheese"
| "corn chowder"
| "cooked icing"
| "comfort food"
| "coconut rice"
| "city chicken"
| "cinnamon bun"
| "chicken soup"
| "chicken mull"
| "chicken feet"
| "chicken rice"
| "chicken kiev"
| "chia pudding"
| "chhena jhili"
| "cherry sauce"
| "cheeseburger"
| "cheese puffs"
| "cheese fries"
| "cheese dream"
| "cheese stick"
| "cheese sauce"
| "cheddar soup"
| "carrot salad"
| "cake/cupcake"
| "caesar salad"
| "cabbage roll"
| "butter sauce"
| "braised beef"
| "blätterteig"
| "bi pong moun"
| "baked potato"
| "baghali polo"
| "bagara khana"
| "baba ganoush"
| "arroz tapado"
| "arroz chaufa"
| "apple butter"
| "yogurt dish"
| "yellow cake"
| "whoopie pie"
| "whole wheat"
| "white sauce"
| "wheat bread"
| "warm tomato"
| "vodka sauce"
| "vinaigrette"
| "twice baked"
| "tres leches"
| "tertiflette"
| "tartiflette"
| "tarte tatin"
| "tagliatelle"
| "sticky buns"
| "steamed bun"
| "starch dish"
| "sponge cake"
| "salsa verde"
| "quick bread"
| "pumpkin pie"
| "pumpkin dip"
| "pulled port"
| "pulled pork"
| "potstickers"
| "poached egg"
| "pizza sauce"
| "pizza dough"
| "pasta sauce"
| "pasta salad"
| "pappardelle"
| "panna cotta"
| "pad kee mao"
| "orecchiette"
| "onion rings"
| "matzo balls"
| "marshmellow"
| "maple cream"
| "magic sauce"
| "honey glaze"
| "green salad"
| "green curry"
| "gingerbread"
| "ginger snap"
| "ginger beer"
| "garden roll"
| "fruit salad"
| "fried dough"
| "fall spread"
| "fall quiche"
| "fall muffin"
| "fall cookie"
| "energy bars"
| "dried fruit"
| "cream sauce"
| "corned beef"
| "coffee cake"
| "chili fries"
| "cheese dish"
| "cheese ball"
| "charcuterie"
| "carrot soup"
| "carrot cake"
| "cake batter"
| "buterscotch"
| "bourguignon"
| "bloody mary"
| "baked pasta"
| "autumn soup"
| "asian salad"
| "apricot jam"
| "apple spice"
| "agua fresca"
| "yeast bread"
| "winter stew"
| "winter soup"
| "whole grain"
| "wheat salad"
| "vichyssoise"
| "upside down"
| "turnip cake"
| "turkey soup"
| "tomato soup"
| "tirokafteri"
| "thai salads"
| "steak sauce"
| "spring roll"
| "spinach pie"
| "spinach dip"
| "spiced nuts"
| "spice bread"
| "spice blend"
| "spanakopita"
| "sorrel soup"
| "smoked fish"
| "shwe htamin"
| "shrimp soup"
| "short bread"
| "sholeh zard"
| "savory tart"
| "saltimbocca"
| "royal icing"
| "risalamande"
| "rice congee"
| "ratatouille"
| "quesadillas"
| "queijadinha"
| "pumpkin bar"
| "puffed rice"
| "puff pastry"
| "protein bar"
| "potato soup"
| "pizza crust"
| "pfennkuchen"
| "pfannkuchen"
| "peach crisp"
| "pasta dough"
| "panne cotte"
| "nasi paprik"
| "nasi kuning"
| "nasi kucing"
| "nasi kerabu"
| "nasi kebuli"
| "nasi kandar"
| "nasi goreng"
| "nasi bogana"
| "nasi ambeng"
| "nasi padang"
| "nasi dagang"
| "nasi campur"
| "mulled wine"
| "mixed drink"
| "matzoh ball"
| "loobia polo"
| "llapingacho"
| "lemon glaze"
| "khao na pet"
| "khao kha mu"
| "katsu curry"
| "kasseropita"
| "jollof rice"
| "hot chicken"
| "heotjesabap"
| "gulab jamun"
| "greek salad"
| "granola bar"
| "giardiniera"
| "gallo pinto"
| "ful medames"
| "fish sticks"
| "enchilladas"
| "dutch apple"
| "dried apple"
| "cookie bowl"
| "cod as food"
| "ci fan tuan"
| "chimichurri"
| "chimichanga"
| "chile sauce"
| "chicken pie"
| "chicken bog"
| "chhena poda"
| "chhena gaja"
| "cheesesteak"
| "cheese slaw"
| "cheese roll"
| "cheese maki"
| "cheese soup"
| "cheese puff"
| "celery soup"
| "caldo verde"
| "buttercream"
| "blue cheese"
| "benedictine"
| "baked fries"
| "baked beans"
| "baked apple"
| "arroz negro"
| "arroz caldo"
| "apple salad"
| "apple crumb"
| "apple crisp"
| "apple cider"
| "apple bread"
| "angel bites"
| "yellowcake"
| "wine sauce"
| "whoopiepie"
| "wellington"
| "tortellini"
| "tomato pie"
| "tetrazzini"
| "tater tots"
| "sweet roll"
| "stroganoff"
| "sticky bun"
| "squid dish"
| "spicy tofu"
| "speculooos"
| "sloppy joe"
| "shortcrust"
| "semifreddo"
| "seasonaing"
| "scaloppine"
| "savory pie"
| "roast beef"
| "rice salad"
| "rice pilaf"
| "red velvet"
| "quickbread"
| "quesadilla"
| "puttanesca"
| "preserving"
| "pound cake"
| "pork chops"
| "pear salad"
| "panzanella"
| "open-faced"
| "on a stick"
| "nut butter"
| "minestrone"
| "meat sauce"
| "meat salad"
| "meat roast"
| "lemoncello"
| "lemon loaf"
| "lemon curd"
| "iced drink"
| "hush puppy"
| "honey cake"
| "grits dish"
| "gingersnap"
| "fudgesicle"
| "frozen pie"
| "frittatina"
| "flat bread"
| "financiers"
| "fettuccine"
| "fall treat"
| "fall snack"
| "fall salad"
| "fall bread"
| "enchiladas"
| "cookie bar"
| "coffeecake"
| "choc chunk"
| "chewy bars"
| "casseroles"
| "cappuccino"
| "candy bars"
| "bundt cake"
| "bruschetta"
| "bravčové"
| "beef steak"
| "battenberg"
| "baked fish"
| "asian soup"
| "apple stew"
| "apple soup"
| "apple cake"
| "apple bake"
| "angel food"
| "albondihas"
| "zeera rice"
| "white rice"
| "warm salad"
| "vinegrette"
| "vegetables"
| "thanh nien"
| "tamale pie"
| "taco sauce"
| "springroll"
| "spicy soup"
| "spice cake"
| "soda bread"
| "smoked ham"
| "shortbread"
| "sauerkraut"
| "sandwiches"
| "sabzi polo"
| "rijsttafel"
| "puppy chow"
| "puliyogare"
| "potato pie"
| "piccalilli"
| "pear salsa"
| "peach tart"
| "patty melt"
| "parmigiana"
| "panta bhat"
| "pad see ew"
| "onion ring"
| "nasi pecel"
| "nasi liwet"
| "nasi lemak"
| "nasi gurih"
| "milk shake"
| "meigan cai"
| "mayonnaise"
| "maple slaw"
| "lor mai ka"
| "lo mai gai"
| "limoncello"
| "lemon cake"
| "kori rotti"
| "khachapuri"
| "keshi yena"
| "kande pohe"
| "jeonbokjuk"
| "jeera rice"
| "hoedeopbap"
| "havij polo"
| "hash brown"
| "garaetteok"
| "fruit cake"
| "fruit bars"
| "fried rice"
| "fried fish"
| "french dip"
| "fish curry"
| "fish stock"
| "energy bar"
| "empanizado"
| "ema datshi"
| "dough ball"
| "dirty rice"
| "curry rice"
| "curd snack"
| "cream soup"
| "cream puff"
| "cream cake"
| "crab cakes"
| "coq au vin"
| "cobb salad"
| "chwee kueh"
| "chicken 65"
| "cheesecake"
| "cheese dog"
| "cheese bun"
| "cheese dip"
| "champorado"
| "chai latte"
| "cereal bar"
| "cauli rice"
| "bubur ayam"
| "brown rice"
| "breadstick"
| "bread bowl"
| "bokkeumbap"
| "blood soup"
| "beef stock"
| "beef broth"
| "bar cookie"
| "baked good"
| "arab salad"
| "applesauce"
| "akki rotti"
| "turnovers"
| "trail mix"
| "sweet tea"
| "succotash"
| "steak pie"
| "spaghetti"
| "snack mix"
| "smoothies"
| "shortcake"
| "schnitzel"
| "sandwich]"
| "rosewater"
| "rice dish"
| "rib sauce"
| "remoulade"
| "red sauce"
| "red curry"
| "preserves"
| "preserved"
| "pork chop"
| "popsicles"
| "pecan pie"
| "osso buco"
| "milkshake"
| "meatballs"
| "meat ribs"
| "mayonaise"
| "marmalade"
| "marinades"
| "margarita"
| "madeleine"
| "ice cream"
| "hot drink"
| "honey bun"
| "hand pies"
| "fruitcake"
| "frittatas"
| "fricassee"
| "flatbread"
| "fish dish"
| "fish cake"
| "fall stew"
| "fall soup"
| "fall cake"
| "fake meat"
| "enchildas"
| "enchilada"
| "dumplings"
| "croquette"
| "cream pie"
| "condiment"
| "cold soup"
| "choc chip"
| "chili mac"
| "charlotte"
| "cassoulet"
| "casserole"
| "carpaccio"
| "cappucino"
| "candy bar"
| "buttercup"
| "bolognese"
| "beef stew"
| "bbq sauce"
| "apple dip"
| "antipasti"
| "yay monte"
| "yakimochi"
| "tortillas"
| "tea cakes"
| "tea bread"
| "tabbouleh"
| "stromboli"
| "spice rub"
| "spice mix"
| "sourdough"
| "songpyeon"
| "seasoning"
| "sandwhich"
| "san pyote"
| "rib roast"
| "ras malai"
| "puliogare"
| "provoleta"
| "pot roast"
| "pierogies"
| "pie crust"
| "paniyaram"
| "nut bread"
| "neuchatel"
| "nasi ulam"
| "nasi uduk"
| "mujaddara"
| "mosaranna"
| "meat loaf"
| "loco moco"
| "kosambari"
| "kamameshi"
| "jucy lucy"
| "jiu niang"
| "java chip"
| "jambalaya"
| "hauskyjza"
| "hamburger"
| "guacamole"
| "gremolata"
| "glühwein"
| "gel icing"
| "gangjeong"
| "fry bread"
| "frito pie"
| "foccaccia"
| "flour mix"
| "fish stew"
| "fish head"
| "fish bowl"
| "fish taco"
| "enchilida"
| "empanadas"
| "egg salad"
| "curd rice"
| "croissant"
| "crab cake"
| "cornbread"
| "cole slaw"
| "cocktails"
| "ciambotta"
| "chitranna"
| "chili dog"
| "carbonara"
| "bora saul"
| "blackened"
| "beer soup"
| "au gratin"
| "apple pie"
| "aloo gobi"
| "aavakaaya"
| "wrappers"
| "tzatziki"
| "truffles"
| "tortilla"
| "tiramisu"
| "timballo"
| "tartlets"
| "taquitos"
| "tapenade"
| "tandoori"
| "stuffing"
| "streusel"
| "stir-fry"
| "spritzer"
| "smoothie"
| "sherbert"
| "sandwich"
| "rootbeer"
| "rissotto"
| "rigatoni"
| "rellenos"
| "porridge"
| "popsicle"
| "popovers"
| "pb&amp"
| "pad thai"
| "ossobuco"
| "oat ball"
| "napoleon"
| "mug cake"
| "moon pie"
| "mini pie"
| "meuniere"
| "meringue"
| "meatloaf"
| "macaroon"
| "macarons"
| "linguine"
| "lemonade"
| "insalata"
| "hot dogs"
| "haroseth"
| "hand pie"
| "gazpacho"
| "galobkes"
| "funfetti"
| "fritters"
| "frittata"
| "focaccia"
| "fishcake"
| "farfalle"
| "fall pie"
| "fall dip"
| "falafels"
| "expresso"
| "empanada"
| "egg dish"
| "dumpling"
| "doughnut"
| "daiquiri"
| "cupcakes"
| "croutons"
| "crostini"
| "crostata"
| "crackers"
| "cocktail"
| "chia egg"
| "chex mix"
| "chai tea"
| "caponata"
| "cake mix"
| "buckeyes"
| "biscotti"
| "beverage"
| "barbecue"
| "baklazan"
| "yule log"
| "vegetais"
| "vegetabe"
| "tiropita"
| "tinutuan"
| "teriyaki"
| "tekkadon"
| "tarakjuk"
| "tangyuan"
| "taco pie"
| "taco dip"
| "suan cai"
| "stir fry"
| "spätzle"
| "spaetzle"
| "shawarma"
| "sel roti"
| "saganaki"
| "rum ball"
| "rasgulla"
| "rasabali"
| "raclette"
| "quesillo"
| "pulihora"
| "pretzels"
| "pralines"
| "pop tart"
| "poor boy"
| "pea soup"
| "pastrami"
| "pancakes"
| "oyakodon"
| "omelette"
| "nurungji"
| "nian gao"
| "nasi tim"
| "moussaka"
| "milanesa"
| "meatball"
| "mcmuffin"
| "marzipan"
| "marinara"
| "marinade"
| "liptauer"
| "kutsinta"
| "kiribath"
| "kinilnat"
| "khao tom"
| "khao mok"
| "khao lam"
| "kedgeree"
| "katsudon"
| "jin deui"
| "injeolmi"
| "ikameshi"
| "iced tea"
| "ice crea"
| "horchata"
| "hobakjuk"
| "hellimli"
| "gratäng"
| "frosting"
| "foccacia"
| "farinata"
| "ensalada"
| "egg roll"
| "dressing"
| "delicacy"
| "dan bauk"
| "dal bhat"
| "corn dog"
| "coleslaw"
| "ciabatta"
| "carnitas"
| "cake pop"
| "cabidela"
| "bizcocho"
| "bibingka"
| "bibimbap"
| "bechemel"
| "bean dip"
| "arancini"
| "amaretti"
| "agemochi"
| "won ton"
| "whipped"
| "waffles"
| "tostada"
| "tom yum"
| "terrine"
| "tempura"
| "tartlet"
| "tartine"
| "tartare"
| "stuffed"
| "strudel"
| "stifado"
| "steamed"
| "souffle"
| "s'mores"
| "skewers"
| "sherbet"
| "sauteed"
| "sangria"
| "roasted"
| "ravioli"
| "pudding"
| "pretzel"
| "praline"
| "pot pie"
| "polenta"
| "poached"
| "pierogi"
| "piergoi"
| "pickles"
| "pavlova"
| "parfait"
| "pancake"
| "oatcake"
| "nuggets"
| "noodles"
| "martini"
| "lolipop"
| "lo mein"
| "limeade"
| "lasagna"
| "ketchup"
| "ice pop"
| "hot dog"
| "harissa"
| "grilled"
| "granola"
| "granita"
| "goulash"
| "gnocchi"
| "gelatin"
| "ganache"
| "galette"
| "fritter"
| "fondant"
| "falafel"
| "fajitas"
| "fagioli"
| "custard"
| "curried"
| "crumble"
| "creamed"
| "compote"
| "cobbler"
| "chutney"
| "churros"
| "chowder"
| "ceviche"
| "caprese"
| "cannoli"
| "burrito"
| "brownie"
| "bon bon"
| "blondie"
| "biscuit"
| "baklava"
| "zha cai"
| "veggies"
| "undhiyu"
| "tumpeng"
| "topping"
| "theeyal"
| "syrniki"
| "squares"
| "spreads"
| "sonoran"
| "sliders"
| "siu mei"
| "shooter"
| "sekihan"
| "seafood"
| "scuffin"
| "schmear"
| "sashimi"
| "risotto"
| "rangoon"
| "quesito"
| "poutine"
| "poriyal"
| "popcorn"
| "piccata"
| "pastizz"
| "pao cai"
| "palitaw"
| "ostkaka"
| "onigiri"
| "omurice"
| "obatzda"
| "oatmeal"
| "nicoise"
| "moretum"
| "mont di"
| "marsala"
| "maqluba"
| "lontong"
| "lasagne"
| "kushari"
| "kuluban"
| "kongbap"
| "khichdi"
| "ketupat"
| "karedok"
| "kalamay"
| "healthy"
| "gai fan"
| "fonduta"
| "far far"
| "espasol"
| "eggroll"
| "egg nog"
| "donburi"
| "dim sum"
| "daifuku"
| "cupcake"
| "cracker"
| "chicken"
| "chewies"
| "chazuke"
| "challah"
| "chalbap"
| "calzone"
| "buttons"
| "bun cha"
| "bulgogi"
| "breaded"
| "borscht"
| "boribap"
| "bo ssam"
| "biryani"
| "beignet"
| "banh mi"
| "bai cha"
| "bahn mi"
| "alfredo"
| "alcohol"
| "7 layer"
| "wonton"
| "veggie"
| "turtle"
| "trifle"
| "toffee"
| "tartar"
| "tamale"
| "tagine"
| "sundae"
| "strata"
| "spread"
| "sponge"
| "sorbet"
| "smores"
| "skewer"
| "seared"
| "scones"
| "samosa"
| "samoas"
| "relish"
| "ragout"
| "quiche"
| "posole"
| "panini"
| "omlete"
| "omelet"
| "nougat"
| "muffin"
| "muesli"
| "mousse"
| "mashed"
| "masala"
| "linzer"
| "latkes"
| "labneh"
| "kebobs"
| "jummus"
| "hummus"
| "gratin"
| "glazed"
| "gelato"
| "fajita"
| "cutlet"
| "crepes"
| "cookie"
| "cobler"
| "chilli"
| "cheesy"
| "ceasar"
| "burger"
| "brulee"
| "braise"
| "borsch"
| "bisque"
| "batter"
| "zongzi"
| "yaksik"
| "waffle"
| "unadon"
| "thoran"
| "tahdig"
| "starch"
| "s'more"
| "slider"
| "siopao"
| "serabi"
| "sauces"
| "sambal"
| "salads"
| "rollup"
| "reuben"
| "potpie"
| "pongal"
| "pastry"
| "paskha"
| "paella"
| "nachos"
| "mojito"
| "matzoh"
| "mansaf"
| "lumpia"
| "lemper"
| "lemang"
| "lamban"
| "kuchen"
| "kralan"
| "kimchi"
| "kebabs"
| "jatjuk"
| "gimbap"
| "gateau"
| "fudges"
| "fondue"
| "erkuai"
| "congee"
| "cereal"
| "caesar"
| "burasa"
| "budget"
| "bhurta"
| "arepas"
| "aligot"
| "zuppa"
| "wraps"
| "wings"
| "torte"
| "torta"
| "toast"
| "tarts"
| "tarte"
| "tarta"
| "tapas"
| "stock"
| "stews"
| "smash"
| "shake"
| "samoa"
| "salsa"
| "rolls"
| "ramen"
| "raita"
| "punch"
| "pesto"
| "penne"
| "pasta"
| "migas"
| "laksa"
| "labne"
| "korma"
| "kebab"
| "kalbi"
| "kabob"
| "juice"
| "jelly"
| "icing"
| "gulas"
| "gnudi"
| "fudge"
| "fries"
| "fried"
| "float"
| "dairy"
| "curry"
| "crust"
| "crumb"
| "crudo"
| "crisp"
| "creme"
| "chips"
| "broth"
| "brine"
| "bread"
| "brats"
| "babka"
| "aioli"
| "zosui"
| "zerde"
| "zarda"
| "tteok"
| "tacos"
| "sushi"
| "suman"
| "scone"
| "sauce"
| "sarma"
| "salad"
| "rojak"
| "ranch"
| "puttu"
| "pizza"
| "pilaf"
| "pares"
| "nacho"
| "mochi"
| "mandi"
| "lugaw"
| "lokri"
| "lepet"
| "latte"
| "kugel"
| "kheer"
| "kateh"
| "kabab"
| "jello"
| "halva"
| "guoba"
| "gumbo"
| "gujia"
| "gravy"
| "glaze"
| "frico"
| "drink"
| "dough"
| "dolma"
| "dodol"
| "crepe"
| "churu"
| "chili"
| "carri"
| "candy"
| "barfi"
| "bagel"
| "adobo"
| "ziti"
| "wrap"
| "tort"
| "tart"
| "stew"
| "soup"
| "soda"
| "soba"
| "slaw"
| "rubs"
| "roux"
| "roll"
| "ragu"
| "pops"
| "pate"
| "orzo"
| "mayo"
| "hash"
| "gyro"
| "flan"
| "dips"
| "dhal"
| "daal"
| "curd"
| "chai"
| "cake"
| "buns"
| "baba"
| "utan"
| "urap"
| "taco"
| "puto"
| "puso"
| "puff"
| "plov"
| "pies"
| "pets"
| "peda"
| "naan"
| "mole"
| "jerk"
| "idli"
| "dosa"
| "cobb"
| "bolo"
| "biko"
| "bhat"
| "bark"
| "pie"
| "jam"
| "dip"
| "dal"
| "pho"
| "juk"
| "bar"





 
%state TK, ET

%%

<YYINITIAL,ET> {
   {AnySpace}         {  yybegin(TK);  return getToken( TokenClass.SPACE );  }
   .                   { yybegin( ET ); return  getToken( TokenClass.TEXT ); }
}

<TK> {
 {DISH}               { yybegin( ET );  yypushback ( 1 );      return getToken( TokenClass.DISH );      }
 {ADJ}                { yybegin (ET);   yypushback( 1 );       return getToken( TokenClass.ADJ );       }
 \w+                  {  yybegin( ET );                        return getToken( TokenClass.OTHER);      }
  .                    { yybegin( ET ); return getToken( TokenClass.TEXT ); }
}

