package com.mfe.parser;



public enum TokenClass {
  EOF, NUMBER, MG, ML, INCH,PINT,KILO,FOOD_OR_PORTION, FOOD, DISH, O,ABREV,
  INTEGER, OTHER, FRACTION, MEASURE, ADJ , AMOUNT, TEXT, LINE, PORTION, SPACE, DECFRAC,
  BLANK, RECIPE_START, RECIPE_END, TITLE, YIELD, CATEGORY, ATTRIBUTION, EOL,
  CUP,LITER,GRAM,OZ,QUART,TSP,TBL,GALLON,SUB_TITLE,BULLET, LB, INGRED_SUB_LIST,
  SIZE, HINT, RPAREN, LPAREN, PINCH
}
